#!/bin/bash
#
# A convenience django-admin wrapper, which sets up environment
# variables read from files in a project's var/env/ directory and sets
# PYTHONPATH to a src/ directory under the project, if it exists.


# If a Python virtual environment with an associated project (typically
# set by Virtualenvwrapper) is activated...
if [ -n "$VIRTUAL_ENV" -a -f "$VIRTUAL_ENV/.project" ]; then
    project_dir=$(cat "$VIRTUAL_ENV/.project")

    # If a var/env/ directory exists under the project directory, read
    # the contents of all files under that directory into exported
    # environment variables that take the names of the files.
    if [ -d "$project_dir/var/env" ]; then
        envfile_dir="$project_dir/var/env"
        for file in "$envfile_dir"/*
        do
            file_name=${file##*/}
            export $file_name="$(cat $file)"
        done
    fi

    # Add the src/ directory under the project to the front of
    # PYTHONPATH, if such a directory exists.
    if [ -d "$project_dir/src" ]; then
        if [ -z "$PYTHONPATH" ]; then
            PYTHONPATH="$project_dir/src"
        else
            PYTHONPATH="$project_dir/src:$PYTHONPATH"
        fi
        export PYTHONPATH
    fi
fi

# Run django-admin with the given arguments.
django-admin "$@"
