#!/bin/bash
#
# Find git repos under the current directory and `git status --short` in them
#

for file in `find . -name '.git' -type d`; do
    echo '--' ${file%/*}
    pushd ${file%/*} &> /dev/null &&\
        git status --short
        popd &> /dev/null
done
