#!/bin/bash
#
# Find git repos under the current directory and `git pull` in them
#

for file in `find . -name '.git' -type d`; do
    echo '--' ${file%/*}
    pushd ${file%/*} &> /dev/null &&\
        git pull
        popd &> /dev/null
done
