#!/bin/bash
#
# Shortcut wrapper for Mosh. The first argument is the target server
# and the second argument names a screen session to resume, focusing
# on the window list.

if [ $# -eq 0 ]; then
    echo "Usage: msh address [screen_session]"
elif [ $# -eq 1 ]; then
    eval mosh -- "$1"
else
    eval mosh -- "$1" screen -x ${@:2} -p '='
fi
