#!/bin/bash
#
# Shortcut wrapper for Mosh. The first argument is the target server.
# If a second argument is given, attempt to resume a GNU Screen session
# starting with that name, with an initial focus on the window list.

if [ $# -eq 0 ]; then
    echo "Usage: msh address [screen_session]"
elif [ $# -eq 1 ]; then
    eval mosh -- "$1"
else
    eval mosh -- "$1" screen -x ${@:2} -p '='
fi
