#!/bin/bash
#
# System package update command. Updates package lists before
# performing any upgrades. Just checks for Homebrew and apt-get.

if type brew &>/dev/null; then
    brew update
    brew upgrade --all
    brew linkapps
fi

if type apt-get &>/dev/null; then
    if [ $(id -u) -ne 0 ]; then
        echo "$0 must be run as root!"
        exit 1
    else
        apt-get update
        apt-get upgrade
    fi
fi
