#!/bin/sh

restore_databases() {
    if [ "$#" -ne 1 ]; then
        echo "Usage: restore-masdash-dbs <backup_file>"
        return 1
    fi

    local backup_file=$1

    tar -xzf ${backup_file}

    for dump_file in *.dump; do
        db_name=$(basename ${dump_file} .dump)
        PGPASSWORD="MasDash4AH293KA02" dropdb -U MasDashUser ${db_name}
        PGPASSWORD="MasDash4AH293KA02" createdb -U MasDashUser ${db_name}
        PGPASSWORD="MasDash4AH293KA02" pg_restore -U MasDashUser -d ${db_name} ${dump_file}
    done

    rm *.dump

    echo "Restore completed from: ${backup_file}"
}

restore_databases "$@"

