#!/bin/bash
#
# Remove *.pyc files under a directory, or the current directory if
# none is specified.
#
# TODO: I really just need a 'recursive rm' that takes a pattern...


if [ "$#" -eq "0" ]; then
    find_dir='./'
else
    find_dir="$@"
fi

find "$find_dir" -name "*.pyc" -exec rm {} \;
