#!/bin/bash
#
# Usage: scr [session_name]
#
# If a screen_name is provided and a session starting with that name
# exists, attach to it. If no such session exists, start a new session
# with that name, using the configuration file ~/.screen/[session_name],
# if such a file exists. Calling without parameters is equivalent to
# calling `scr default`. The search for sessions is case-insensitive.
#
# TODO: Prompt for which screen to resume if [ ! -f ~/.screen/default ]
# TODO: Prompt if multiple screens match given session_name


session_name=${1:-default}
command_options=

# If more than one argument given, just pass it to `screen` and bow out
if [ $# -ge 2 ] || [ "${1:0:1}" == '-' ]; then
   screen "$@"
   exit $?
fi

# If the named screen exists, attach to it
screen_list="$(screen -list)"
found_screen="$(echo "$screen_list" |\
                grep -im1 "\.$session_name[^ ]" |\
                awk '{print $1;}')"

if [ -n "$found_screen" ]; then
    screen -x "$found_screen" -p '='
    exit $?
fi

# It doesn't exist; see if a matching configuration file exists
if [ -f ~/.screen/"$session_name" ]; then
    command_options="-c ~/.screen/$session_name"
fi

eval screen $command_options -S \"$session_name\" -p '='
