#!/bin/bash

supervisorctl stop salt-minion    
supervisorctl stop salt-master
cd /opt/salt/salt &&\
    find ./ -name “*.pyc” -exec rm {} \;
supervisorctl start salt-master
supervisorctl start salt-minion
