#!/bin/bash
#
# Hide a file from Finder and create an alias to it in ~/Documents/Hidden


#$ osascript -e 'tell application "Finder" to make alias file to POSIX file "/file/to/make/link/from" at POSIX file "/folder/where/to/make/link"'

#$ osascript -e 'tell application "Finder" to make alias file to POSIX file "/Applications/Xcode.app/Contents/Applications/OpenGL ES Performance Detective.app" at POSIX file "/Users/mylogin/Applications"'

#————

#
# TODO: Remember to pipe the output to /dev/null


> osascript -e 'tell application "Finder" to make alias file to POSIX file "/Users/hipikat/Zomboid" at POSIX file "/Users/hipikat/Documents/Hidden"'
alias file Zomboid of folder Hidden of folder Documents of folder hipikat of folder Users of startup disk

> SetFile -a V /Users/hipikat/Zomboid

