#!/bin/bash -i
#
# Usage: sniphistory [number_of_commands_ago ...]
#
# With no arguments, echo history numbered down to the most recent
# command (1) and prompt for lines to delete from the history file.
# Arguments should be separated by spaces. If number_of_commands_ago
# is provided, just delete those from the history.
#
# Requires: tac (Gnu Coreutils)
#
# Note: This script relies on bash being invoked in interactive mode
# (see the -i flag to the shebang line), which only works with Bash 4+.
# At the time of writing (2015-02-21), the current version of OS X is
# Yosemite and /bin/bash is 3.2.57. A current version is available via
# Homebrew, so you can either:
#   $ brew install bash
#   $ mv /bin/bash /bin/bash.orig
#   $ ln -s /usr/local/bin/bash /bin/bash
# ... or just change the shebang line to: #!/usr/local/bin/bash -i
#
########################################################################
# Originally packaged under the BSD 2-Clause License at
# https://github.com/hipikat/dotfiles by Adam Wright <adam@hipikat.org>

if [ "$#" -eq 0 ]; then
    HISTTIMEFORMAT= 
    history -a
    history -n
    rev_history=`history | tr -s ' ' | cut -d' ' -f 3- | tac |\
                 awk '{printf("%10d  %s\n", NR, $0)}' - | tac`
    #"$rev_history" | awk '{printf("%10d  %s\n", NR, $0)}' -
    echo "$rev_history"
    #echo "$rev_history"
    #history | tr -s ' ' | cut -d' ' -f 3- | tac
    #echo $HISTFILE
    #echo doing history
    #history
fi
